//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShieldUIDashboardExample {
    
    
    public partial class _Default {
        
        /// <summary>
        /// shieldDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Shield.Web.UI.ShieldDataSource shieldDataSource;
        
        /// <summary>
        /// ShieldGrid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Shield.Web.UI.ShieldGrid ShieldGrid1;
        
        /// <summary>
        /// ShieldChart2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Shield.Web.UI.ShieldChart ShieldChart2;
        
        /// <summary>
        /// ShieldChart3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Shield.Web.UI.ShieldChart ShieldChart3;
        
        /// <summary>
        /// ShieldChart4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Shield.Web.UI.ShieldChart ShieldChart4;
    }
}
